language: php

php:
  - 5.3
  - 5.4
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - sudo apt-get install gdb
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS doctrine_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS doctrine_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database doctrine_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database doctrine_tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS doctrine_tests_tmp;create database IF NOT EXISTS doctrine_tests;'; fi"
  - git submodule update --init

script: cat debug.gdb | sudo gdb --args /home/travis/.phpenv/versions/5.4.8/bin/php /home/travis/.phpenv/versions/5.4.8/bin/phpunit --confugiration tests/travis/$DB.travis.xml
